const types =  {
  GET_PLAYERS_PENDING: "GET_PLAYERS_PENDING",
  GET_PLAYERS_SUCCESS: "GET_PLAYERS_SUCCESS",
  GET_PLAYERS_ERROR: "GET_PLAYERS_ERROR",
  SAVE_PLAYER_PENDING: "SAVE_PLAYER_PENDING",
  SAVE_PLAYER_SUCCESS: "SAVE_PLAYER_SUCCESS",
  SAVE_PLAYER_ERROR: "SAVE_PLAYER_ERROR",
}

export default types;